/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import * as z from "zod"

// Zod Schemas
export const petStatusSchema = z.enum(["available", "pending", "sold"])

export const petCategorySchema = z.enum(["dog", "cat", "bird", "fish", "reptile"])

export const createPetInputSchema = z.object({
  name: z.string(),
  category: petCategorySchema,
  status: petStatusSchema,
  tags: z.array(z.string()),
  photoUrl: z.string().nullish()
})

export const updatePetInputSchema = z.object({
  name: z.string().nullish(),
  category: petCategorySchema.nullish(),
  status: petStatusSchema.nullish(),
  tags: z.array(z.string()).nullish(),
  photoUrl: z.string().nullish()
})

export const petFieldsFragmentSchema = z.object({
  id: z.string(),
  name: z.string(),
  status: petStatusSchema,
  category: petCategorySchema,
  tags: z.array(z.string()),
  photoUrl: z.string().nullish(),
  createdAt: z.string(),
  updatedAt: z.string()
})

export const getPetsQueryVariablesSchema = z.object({
  status: petStatusSchema.nullish(),
  category: petCategorySchema.nullish(),
  limit: z.number().int().nullish(),
  offset: z.number().int().nullish()
})

export const getPetByIdQueryVariablesSchema = z.object({
  id: z.string()
})

export const createPetMutationVariablesSchema = z.object({
  input: createPetInputSchema
})

export const updatePetMutationVariablesSchema = z.object({
  id: z.string(),
  input: updatePetInputSchema
})

export const deletePetMutationVariablesSchema = z.object({
  id: z.string()
})

export const getPetsConnectionQueryVariablesSchema = z.object({
  status: petStatusSchema.nullish(),
  category: petCategorySchema.nullish(),
  first: z.number().int().nullish(),
  after: z.string().nullish()
})

export const getPetsQuerySchema = z.object({
  pets: z.object({
  data: z.array(z.object({
  ...petFieldsFragmentSchema.shape
})),
  total: z.number().int()
})
})

export const getPetByIdQuerySchema = z.object({
  pet: z.object({
  ...petFieldsFragmentSchema.shape
}).nullish()
})

export const createPetMutationSchema = z.object({
  createPet: z.object({
  ...petFieldsFragmentSchema.shape
})
})

export const updatePetMutationSchema = z.object({
  updatePet: z.object({
  ...petFieldsFragmentSchema.shape
}).nullish()
})

export const deletePetMutationSchema = z.object({
  deletePet: z.boolean()
})

export const getPetsConnectionQuerySchema = z.object({
  petsConnection: z.object({
  edges: z.array(z.object({
  node: z.object({
  ...petFieldsFragmentSchema.shape
}),
  cursor: z.string()
})),
  pageInfo: z.object({
  hasNextPage: z.boolean(),
  hasPreviousPage: z.boolean(),
  startCursor: z.string().nullish(),
  endCursor: z.string().nullish()
}),
  totalCount: z.number().int()
})
})

// TypeScript Types (inferred from Zod schemas)
export type PetStatus = z.infer<typeof petStatusSchema>
export type PetCategory = z.infer<typeof petCategorySchema>
export type CreatePetInput = z.infer<typeof createPetInputSchema>
export type UpdatePetInput = z.infer<typeof updatePetInputSchema>
export type PetFieldsFragment = z.infer<typeof petFieldsFragmentSchema>
export type GetPetsQueryVariables = z.infer<typeof getPetsQueryVariablesSchema>
export type GetPetByIdQueryVariables = z.infer<typeof getPetByIdQueryVariablesSchema>
export type CreatePetMutationVariables = z.infer<typeof createPetMutationVariablesSchema>
export type UpdatePetMutationVariables = z.infer<typeof updatePetMutationVariablesSchema>
export type DeletePetMutationVariables = z.infer<typeof deletePetMutationVariablesSchema>
export type GetPetsConnectionQueryVariables = z.infer<typeof getPetsConnectionQueryVariablesSchema>
export type GetPetsQuery = z.infer<typeof getPetsQuerySchema>
export type GetPetByIdQuery = z.infer<typeof getPetByIdQuerySchema>
export type CreatePetMutation = z.infer<typeof createPetMutationSchema>
export type UpdatePetMutation = z.infer<typeof updatePetMutationSchema>
export type DeletePetMutation = z.infer<typeof deletePetMutationSchema>
export type GetPetsConnectionQuery = z.infer<typeof getPetsConnectionQuerySchema>
