import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { loadDocuments } from "../core/documents";
import { generateFunctions } from "./functions";

const fixturesDir = resolve(__dirname, "../test/fixtures/graphql");

describe("generateFunctions", () => {
  it("generates functions file with eslint-disable comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("/* eslint-disable */");
  });

  it("generates functions file with auto-generated comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("auto-generated by tangrams");
  });

  it("imports getClient from the specified client path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./schema",
    });

    expect(result).toContain('import { getClient } from "../client"');
  });

  it("imports types from the specified types path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./custom-schema",
    });

    expect(result).toContain('} from "./custom-schema"');
  });

  it("generates fragment documents when fragments exist", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("// Fragment Documents");
    expect(result).toContain("const UserFieldsFragmentDoc");
    expect(result).toContain("fragment UserFields on User");
  });

  it("generates operation documents", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("// Documents");
    expect(result).toContain("const GetUserDocument");
    expect(result).toContain("const ListUsersDocument");
    expect(result).toContain("const CreateUserDocument");
  });

  it("concatenates fragment dependencies in operation documents", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    // Operations that use UserFields fragment should interpolate it via template literal
    // biome-ignore lint/suspicious/noTemplateCurlyInString: testing for literal template string output
    expect(result).toContain("${UserFieldsFragmentDoc}`");
  });

  it("generates standalone query functions", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("// Functions");
    expect(result).toContain("export const getUser = async");
    expect(result).toContain("export const listUsers = async");
  });

  it("generates standalone mutation functions", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("export const createUser = async");
    expect(result).toContain("export const updateUser = async");
    expect(result).toContain("export const deleteUser = async");
  });

  it("handles operations with required variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    // GetUser has required $id variable
    expect(result).toContain(
      "getUser = async (variables: GetUserQueryVariables)",
    );
  });

  it("handles operations with optional variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    // ListUsers has all optional variables ($limit: Int, $offset: Int)
    expect(result).toContain(
      "listUsers = async (variables?: ListUsersQueryVariables)",
    );
  });

  it("handles mutations with required variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    // CreateUser has required $input variable
    expect(result).toContain(
      "createUser = async (variables: CreateUserMutationVariables)",
    );
  });

  it("imports query response types", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("GetUserQuery,");
    expect(result).toContain("ListUsersQuery,");
  });

  it("imports mutation response types", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("CreateUserMutation,");
    expect(result).toContain("UpdateUserMutation,");
    expect(result).toContain("DeleteUserMutation,");
  });

  it("imports variable types for operations with variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("GetUserQueryVariables,");
    expect(result).toContain("ListUsersQueryVariables,");
    expect(result).toContain("CreateUserMutationVariables,");
  });

  it("uses correct generic type in request call for queries", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain(".request<GetUserQuery>(GetUserDocument");
    expect(result).toContain(".request<ListUsersQuery>(ListUsersDocument");
  });

  it("uses correct generic type in request call for mutations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain(".request<CreateUserMutation>(CreateUserDocument");
    expect(result).toContain(".request<UpdateUserMutation>(UpdateUserDocument");
  });

  it("handles query-only documents", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("export const getUserById = async");
    expect(result).toContain("export const getAllUsers = async");
    expect(result).not.toContain("Mutation");
  });

  it("handles mutation-only documents", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toContain("export const createNewUser = async");
    expect(result).toContain("export const resetAllUsers = async");
    expect(result).not.toContain("Query,");
  });

  it("handles operations without variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    // GetAllUsers has no variables
    expect(result).toContain("getAllUsers = async ()");
    expect(result).toContain(".request<GetAllUsersQuery>(GetAllUsersDocument)");
  });

  it("handles mutation without variables", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    // ResetAllUsers has no variables
    expect(result).toContain("resetAllUsers = async ()");
    expect(result).toContain(
      ".request<ResetAllUsersMutation>(ResetAllUsersDocument)",
    );
  });

  it("does not generate fragment section when no fragments exist", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).not.toContain("// Fragment Documents");
    expect(result).not.toContain("FragmentDoc");
  });

  it("matches snapshot for user functions", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toMatchSnapshot();
  });

  it("matches snapshot for query-only functions", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toMatchSnapshot();
  });

  it("matches snapshot for mutation-only functions", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateFunctions({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./schema",
    });

    expect(result).toMatchSnapshot();
  });
});
