/**
 * GraphQL standalone functions generation
 *
 * Generates standalone async fetch functions for GraphQL operations.
 * These functions are imported by both operations.ts (for queryOptions/mutationOptions)
 * and collections.ts (for TanStack DB persistence handlers).
 */

import { getFragmentDependencies } from "../core/documents";
import {
  toCamelCase,
  toDocumentName,
  toFragmentDocName,
  toMutationTypeName,
  toMutationVariablesTypeName,
  toQueryTypeName,
  toQueryVariablesTypeName,
} from "../utils/naming";

import type {
  ParsedDocuments,
  ParsedFragment,
  ParsedOperation,
} from "../core/documents";

export interface FunctionsGeneratorOptions {
  documents: ParsedDocuments;
  clientImportPath: string;
  typesImportPath: string;
}

/**
 * Generate the functions file with standalone fetch functions
 */
export function generateFunctions(options: FunctionsGeneratorOptions): string {
  const { documents, clientImportPath, typesImportPath } = options;
  const { operations, fragments } = documents;

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("/* This file is auto-generated by tangrams. Do not edit. */");
  lines.push("");

  // Import client
  lines.push(`import { getClient } from "${clientImportPath}"`);
  lines.push("");

  // Type imports
  const typeImports = generateTypeImports(operations);
  if (typeImports) {
    lines.push("import type {");
    lines.push(typeImports);
    lines.push(`} from "${typesImportPath}"`);
    lines.push("");
  }

  // Fragment documents
  if (fragments.length > 0) {
    lines.push("// Fragment Documents");
    for (const fragment of fragments) {
      lines.push(generateFragmentDocument(fragment));
      lines.push("");
    }
  }

  // Operation documents
  lines.push("// Documents");
  for (const operation of operations) {
    const fragmentDeps = getFragmentDependencies(operation, fragments);
    lines.push(generateOperationDocument(operation, fragmentDeps));
    lines.push("");
  }

  // Standalone functions
  lines.push("// Functions");
  for (const operation of operations) {
    if (operation.operation === "query") {
      lines.push(generateQueryFunction(operation));
    } else {
      lines.push(generateMutationFunction(operation));
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate type imports for all operations (response and variable types)
 */
function generateTypeImports(operations: ParsedOperation[]): string {
  const imports: string[] = [];

  for (const op of operations) {
    const hasVariables =
      op.node.variableDefinitions && op.node.variableDefinitions.length > 0;

    if (op.operation === "query") {
      imports.push(`\t${toQueryTypeName(op.name)},`);
      if (hasVariables) {
        imports.push(`\t${toQueryVariablesTypeName(op.name)},`);
      }
    } else if (op.operation === "mutation") {
      imports.push(`\t${toMutationTypeName(op.name)},`);
      if (hasVariables) {
        imports.push(`\t${toMutationVariablesTypeName(op.name)},`);
      }
    }
  }

  return imports.join("\n");
}

/**
 * Generate a fragment document constant
 */
function generateFragmentDocument(fragment: ParsedFragment): string {
  const docName = toFragmentDocName(fragment.name);
  return `const ${docName} = /* GraphQL */ \`
${fragment.document}
\``;
}

/**
 * Generate an operation document constant with fragment dependencies
 */
function generateOperationDocument(
  operation: ParsedOperation,
  fragmentDeps: ParsedFragment[],
): string {
  const docName = toDocumentName(operation.name);

  if (fragmentDeps.length === 0) {
    return `const ${docName} = /* GraphQL */ \`
${operation.document}
\``;
  }

  // Build the document with fragment concatenation
  const fragmentConcats = fragmentDeps
    .map((f) => toFragmentDocName(f.name))
    .join(" + ");

  return `const ${docName} = /* GraphQL */ \`
${operation.document}
\` + ${fragmentConcats}`;
}

/**
 * Generate a standalone async function for a query operation
 */
function generateQueryFunction(operation: ParsedOperation): string {
  const fnName = toCamelCase(operation.name);
  const docName = toDocumentName(operation.name);
  const queryType = toQueryTypeName(operation.name);
  const variablesType = toQueryVariablesTypeName(operation.name);

  const hasVariables =
    operation.node.variableDefinitions &&
    operation.node.variableDefinitions.length > 0;

  // Check if all variables are optional
  const allOptional =
    hasVariables &&
    operation.node.variableDefinitions?.every(
      (v) => v.type.kind !== "NonNullType",
    );

  if (!hasVariables) {
    return `export const ${fnName} = async () =>
	(await getClient()).request<${queryType}>(${docName})`;
  }

  const variableParam = allOptional
    ? `variables?: ${variablesType}`
    : `variables: ${variablesType}`;

  return `export const ${fnName} = async (${variableParam}) =>
	(await getClient()).request<${queryType}>(${docName}, variables ?? undefined)`;
}

/**
 * Generate a standalone async function for a mutation operation
 */
function generateMutationFunction(operation: ParsedOperation): string {
  const fnName = toCamelCase(operation.name);
  const docName = toDocumentName(operation.name);
  const mutationType = toMutationTypeName(operation.name);
  const variablesType = toMutationVariablesTypeName(operation.name);

  const hasVariables =
    operation.node.variableDefinitions &&
    operation.node.variableDefinitions.length > 0;

  if (!hasVariables) {
    return `export const ${fnName} = async () =>
	(await getClient()).request<${mutationType}>(${docName})`;
  }

  return `export const ${fnName} = async (variables: ${variablesType}) =>
	(await getClient()).request<${mutationType}>(${docName}, variables)`;
}
