/**
 * GraphQL operations generation
 *
 * Generates queryOptions and mutationOptions that import standalone
 * fetch functions from functions.ts.
 */

import {
  toCamelCase,
  toMutationOptionsName,
  toMutationVariablesTypeName,
  toQueryOptionsName,
  toQueryVariablesTypeName,
} from "../utils/naming";

import type { ParsedDocuments, ParsedOperation } from "../core/documents";

export interface OperationsGeneratorOptions {
  documents: ParsedDocuments;
  typesImportPath: string;
  /** The source name to include in query/mutation keys */
  sourceName: string;
}

/**
 * Generate the operations file with queryOptions and mutationOptions
 */
/** Hardcoded import path for functions (always ../functions from query/) */
const FUNCTIONS_IMPORT_PATH = "../functions";

export function generateGraphQLOperations(
  options: OperationsGeneratorOptions,
): string {
  const { documents, typesImportPath, sourceName } = options;
  const { operations } = documents;

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("/* This file is auto-generated by tangrams. Do not edit. */");
  lines.push("");

  // Imports
  const hasQueries = operations.some((op) => op.operation === "query");
  const hasMutations = operations.some((op) => op.operation === "mutation");

  const tanstackImports: string[] = [];
  if (hasMutations) tanstackImports.push("mutationOptions");
  if (hasQueries) tanstackImports.push("queryOptions");

  if (tanstackImports.length > 0) {
    lines.push(
      `import { ${tanstackImports.join(", ")} } from "@tanstack/react-query"`,
    );
  }

  // Import functions from functions.ts
  const functionImports = getFunctionImports(operations);
  if (functionImports.length > 0) {
    lines.push(
      `import { ${functionImports.join(", ")} } from "${FUNCTIONS_IMPORT_PATH}"`,
    );
  }
  lines.push("");

  // Type imports (only variable types needed for function signatures)
  const typeImports = generateVariableTypeImports(operations);
  if (typeImports) {
    lines.push("import type {");
    lines.push(typeImports);
    lines.push(`} from "${typesImportPath}"`);
    lines.push("");
  }

  // Generate operations
  lines.push("// Operations");
  for (const operation of operations) {
    if (operation.operation === "query") {
      lines.push(generateQueryOptions(operation, sourceName));
    } else {
      lines.push(generateMutationOptions(operation, sourceName));
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Get function import names for all operations
 */
function getFunctionImports(operations: ParsedOperation[]): string[] {
  return operations.map((op) => toCamelCase(op.name));
}

/**
 * Generate type imports for variable types only
 */
function generateVariableTypeImports(operations: ParsedOperation[]): string {
  const imports: string[] = [];

  for (const op of operations) {
    const hasVariables =
      op.node.variableDefinitions && op.node.variableDefinitions.length > 0;

    if (hasVariables) {
      if (op.operation === "query") {
        imports.push(`\t${toQueryVariablesTypeName(op.name)},`);
      } else if (op.operation === "mutation") {
        imports.push(`\t${toMutationVariablesTypeName(op.name)},`);
      }
    }
  }

  return imports.join("\n");
}

/**
 * Generate queryOptions for a query operation
 */
function generateQueryOptions(
  operation: ParsedOperation,
  sourceName: string,
): string {
  const optionsFnName = toQueryOptionsName(operation.name);
  const fetchFnName = toCamelCase(operation.name);
  const variablesType = toQueryVariablesTypeName(operation.name);

  const hasVariables =
    operation.node.variableDefinitions &&
    operation.node.variableDefinitions.length > 0;

  // Check if all variables are optional
  const allOptional =
    hasVariables &&
    operation.node.variableDefinitions?.every(
      (v) => v.type.kind !== "NonNullType",
    );

  if (!hasVariables) {
    return `export const ${optionsFnName} = () =>
	queryOptions({
		queryKey: ["${sourceName}", "${operation.name}"],
		queryFn: () => ${fetchFnName}(),
	})`;
  }

  const variableParam = allOptional
    ? `variables?: ${variablesType}`
    : `variables: ${variablesType}`;

  return `export const ${optionsFnName} = (${variableParam}) =>
	queryOptions({
		queryKey: ["${sourceName}", "${operation.name}", variables],
		queryFn: () => ${fetchFnName}(variables),
	})`;
}

/**
 * Generate mutationOptions for a mutation operation
 */
function generateMutationOptions(
  operation: ParsedOperation,
  sourceName: string,
): string {
  const optionsFnName = toMutationOptionsName(operation.name);
  const fetchFnName = toCamelCase(operation.name);
  const variablesType = toMutationVariablesTypeName(operation.name);

  const hasVariables =
    operation.node.variableDefinitions &&
    operation.node.variableDefinitions.length > 0;

  if (!hasVariables) {
    return `export const ${optionsFnName} = () =>
	mutationOptions({
		mutationKey: ["${sourceName}", "${operation.name}"],
		mutationFn: () => ${fetchFnName}(),
	})`;
  }

  return `export const ${optionsFnName} = () =>
	mutationOptions({
		mutationKey: ["${sourceName}", "${operation.name}"],
		mutationFn: (variables: ${variablesType}) => ${fetchFnName}(variables),
	})`;
}
