import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { loadDocuments } from "../core/documents";
import { generateGraphQLOperations } from "./query-options";

const fixturesDir = resolve(__dirname, "../test/fixtures/graphql");

describe("generateGraphQLOperations", () => {
  it("generates operations file with eslint-disable comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain("/* eslint-disable */");
  });

  it("generates operations file with auto-generated comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain("auto-generated by tangrams");
  });

  it("imports queryOptions and mutationOptions from @tanstack/react-query", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain(
      'import { mutationOptions, queryOptions } from "@tanstack/react-query"',
    );
  });

  it("imports functions from the hardcoded ../functions path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain('from "../functions"');
  });

  it("imports types from the specified types path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./custom-types",
      sourceName: "test",
    });

    expect(result.content).toContain('} from "./custom-types"');
  });

  it("generates queryOptions for query operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain("export const getUserQueryOptions");
    expect(result.content).toContain("export const listUsersQueryOptions");
  });

  it("generates mutation options for mutation operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain("export const createUserMutationOptions");
    expect(result.content).toContain("export const updateUserMutationOptions");
    expect(result.content).toContain("export const deleteUserMutationOptions");
  });

  it("includes queryKey for query operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain('queryKey: ["test", "GetUser"');
    expect(result.content).toContain('queryKey: ["test", "ListUsers"');
  });

  it("includes mutationKey for mutation operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain('mutationKey: ["test", "CreateUser"]');
    expect(result.content).toContain('mutationKey: ["test", "UpdateUser"]');
  });

  it("handles operations with required variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    // GetUser has required $id variable
    expect(result.content).toContain(
      "getUserQueryOptions = (variables: GetUserQueryVariables)",
    );
  });

  it("handles operations with optional variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    // ListUsers has all optional variables
    expect(result.content).toContain(
      "listUsersQueryOptions = (variables?: ListUsersQueryVariables)",
    );
  });

  it("only imports queryOptions when there are no mutations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain(
      'import { queryOptions } from "@tanstack/react-query"',
    );
    expect(result.content).not.toContain("mutationOptions");
  });

  it("only imports mutationOptions when there are no queries", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toContain(
      'import { mutationOptions } from "@tanstack/react-query"',
    );
    expect(result.content).not.toContain("queryOptions");
  });

  it("calls imported function in queryFn", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    // Should import and call the function from functions.ts
    expect(result.content).toContain("queryFn: () => getUser(variables)");
  });

  it("calls imported function in mutationFn", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    // Should import and call the function from functions.ts
    expect(result.content).toContain(
      "mutationFn: (variables: CreateUserMutationVariables) => createUser(variables)",
    );
  });

  it("matches snapshot for user operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toMatchSnapshot();
  });

  it("matches snapshot for query-only operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toMatchSnapshot();
  });

  it("matches snapshot for mutation-only operations", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result.content).toMatchSnapshot();
  });

  it("returns warnings for paginated queries without schema", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateGraphQLOperations({
      documents,
      typesImportPath: "./types",
      sourceName: "test",
    });

    // ListUsers has limit/offset pagination but no schema to analyze return type
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain("ListUsers");
    expect(result.warnings[0]).toContain("pagination arguments");
  });
});
