import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { loadDocuments } from "@/core/documents";
import { generateStartFunctions } from "./start";

const fixturesDir = resolve(__dirname, "../test/fixtures/graphql");

describe("generateStartFunctions", () => {
  it("generates file with eslint-disable comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("/* eslint-disable */");
  });

  it("generates file with auto-generated comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("auto-generated by tangrams");
  });

  it("imports createServerFn from @tanstack/react-start", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain(
      'import { createServerFn } from "@tanstack/react-start"',
    );
  });

  it("imports getClient from the specified client path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain('import { getClient } from "../client"');
  });

  it("imports types from the specified types path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain('} from "./types"');
  });

  it("generates server function with GET method for queries", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain(
      'export const getUserFn = createServerFn({ method: "GET" })',
    );
    expect(result).toContain(
      'export const listUsersFn = createServerFn({ method: "GET" })',
    );
  });

  it("generates server function with POST method for mutations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain(
      'export const createUserFn = createServerFn({ method: "POST" })',
    );
    expect(result).toContain(
      'export const updateUserFn = createServerFn({ method: "POST" })',
    );
    expect(result).toContain(
      'export const deleteUserFn = createServerFn({ method: "POST" })',
    );
  });

  it("uses inputValidator for operations with variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    // GetUser has required variables
    expect(result).toContain(
      ".inputValidator((data: GetUserQueryVariables) => data)",
    );
  });

  it("does not use inputValidator for operations without variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    // GetAllUsers has no variables, should use handler directly
    expect(result).toContain(
      'export const getAllUsersFn = createServerFn({ method: "GET" })',
    );
    expect(result).toContain(".handler(async () =>");
    // Should NOT have inputValidator for this operation
    expect(result).not.toContain("GetAllUsersQueryVariables");
  });

  it("generates fragment documents", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("// Fragment Documents");
    expect(result).toContain("const UserFieldsFragmentDoc");
  });

  it("generates operation documents", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("const GetUserDocument");
    expect(result).toContain("const CreateUserDocument");
  });

  it("matches snapshot for user operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });

  it("matches snapshot for query-only operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });

  it("matches snapshot for mutation-only operations", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateStartFunctions({
      documents,
      clientImportPath: "../client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });
});
