/**
 * Shared Zod schema generation utilities
 * Used by both OpenAPI and GraphQL adapters to generate Zod schemas
 */

/**
 * Context for Zod schema generation
 * Tracks generated schemas to avoid duplicates and handle dependencies
 */
export interface ZodGenContext {
  /** Track generated schema names to avoid duplicates */
  generatedSchemas: Set<string>;
  /** Track schemas that need to be generated (dependencies) */
  pendingSchemas: Map<string, unknown>;
  /** Generated Zod schema definitions */
  zodSchemas: string[];
  /** Generated TypeScript type exports (inferred from Zod) */
  typeExports: string[];
  /** Warnings during generation */
  warnings: string[];
}

/**
 * Create a new Zod generation context
 */
export function createZodGenContext(): ZodGenContext {
  return {
    generatedSchemas: new Set(),
    pendingSchemas: new Map(),
    zodSchemas: [],
    typeExports: [],
    warnings: [],
  };
}

/**
 * Convert a type name to a Zod schema variable name
 * e.g., "User" -> "userSchema", "CreateUserRequest" -> "createUserRequestSchema"
 */
export function toSchemaName(typeName: string): string {
  const camelCase = typeName.charAt(0).toLowerCase() + typeName.slice(1);
  return `${camelCase}Schema`;
}

/**
 * Convert a string to PascalCase
 * e.g., "create_user" -> "CreateUser", "create-user" -> "CreateUser"
 */
export function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

/**
 * Convert a string to camelCase
 * e.g., "CreateUser" -> "createUser", "create_user" -> "createUser"
 */
export function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/**
 * Check if a property name is a valid JavaScript identifier
 * If not, it needs to be quoted in object literals
 */
export function isValidIdentifier(name: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name);
}

/**
 * Get a safe property name for use in object literals
 * Quotes the name if it's not a valid identifier
 */
export function getSafePropertyName(name: string): string {
  return isValidIdentifier(name) ? name : `"${name}"`;
}

/**
 * Generate the file header for generated Zod schema files
 */
export function generateZodFileHeader(): string[] {
  return [
    "/* eslint-disable */",
    "/* This file is auto-generated by tangen. Do not edit. */",
    "",
    'import * as z from "zod"',
    "",
  ];
}

/**
 * Build the final output from a Zod generation context
 */
export function buildZodOutput(ctx: ZodGenContext): string {
  const lines: string[] = generateZodFileHeader();

  // Add Zod schemas
  if (ctx.zodSchemas.length > 0) {
    lines.push("// Zod Schemas");
    lines.push(...ctx.zodSchemas);
    lines.push("");
  }

  // Add TypeScript type exports (inferred from Zod)
  if (ctx.typeExports.length > 0) {
    lines.push("// TypeScript Types (inferred from Zod schemas)");
    lines.push(...ctx.typeExports);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Add a schema to the context
 */
export function addSchemaToContext(
  ctx: ZodGenContext,
  typeName: string,
  zodType: string,
): void {
  if (ctx.generatedSchemas.has(typeName)) return;

  ctx.generatedSchemas.add(typeName);
  const schemaVarName = toSchemaName(typeName);

  ctx.zodSchemas.push(`export const ${schemaVarName} = ${zodType}`);
  ctx.typeExports.push(
    `export type ${typeName} = z.infer<typeof ${schemaVarName}>`,
  );
}

/**
 * Check if a Zod type string is just a reference to another schema
 * (not an inline z.* definition)
 */
export function isSchemaReference(zodType: string): boolean {
  return (
    !zodType.startsWith("z.") && /^[A-Za-z][A-Za-z0-9]*Schema$/.test(zodType)
  );
}
