/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { infiniteQueryOptions, mutationOptions, queryOptions } from "@tanstack/react-query"

import { createPet, deletePet, getPetById, getPets, getPetsConnection, updatePet } from "../functions"

import type { CreatePetMutationVariables, DeletePetMutationVariables, GetPetByIdQueryVariables, GetPetsConnectionQueryVariables, GetPetsQueryVariables, UpdatePetMutationVariables } from "../schema"

// Query Options
export const getPetsQueryOptions = (variables?: GetPetsQueryVariables) =>
  queryOptions({
  queryKey: ["api", "GetPets", variables],
  queryFn: () => getPets(variables),
})

export const getPetByIdQueryOptions = (variables: GetPetByIdQueryVariables) =>
  queryOptions({
  queryKey: ["api", "GetPetById", variables],
  queryFn: () => getPetById(variables),
})

export const getPetsConnectionQueryOptions = (variables?: GetPetsConnectionQueryVariables) =>
  queryOptions({
  queryKey: ["api", "GetPetsConnection", variables],
  queryFn: () => getPetsConnection(variables),
})

// Infinite Query Options
export const getPetsConnectionInfiniteQueryOptions = (variables?: Omit<GetPetsConnectionQueryVariables, "after">) =>
  infiniteQueryOptions({
  queryKey: ["api", "GetPetsConnection", "infinite", variables],
  queryFn: ({ pageParam }) => getPetsConnection({ ...variables, after: pageParam }),
  initialPageParam: undefined as string | undefined,
  getNextPageParam: (lastPage) => lastPage.petsConnection?.pageInfo?.hasNextPage ? lastPage.petsConnection?.pageInfo?.endCursor : undefined,
})

// Mutation Options
export const createPetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "CreatePet"],
  mutationFn: (variables: CreatePetMutationVariables) => createPet(variables),
})

export const updatePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "UpdatePet"],
  mutationFn: (variables: UpdatePetMutationVariables) => updatePet(variables),
})

export const deletePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "DeletePet"],
  mutationFn: (variables: DeletePetMutationVariables) => deletePet(variables),
})

