/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as PetsEditRouteImport } from './routes/pets/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsEditRoute = PetsEditRouteImport.update({
  id: '/pets/edit',
  path: '/pets/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pets/edit': typeof PetsEditRoute
  '/pets/new': typeof PetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pets/edit': typeof PetsEditRoute
  '/pets/new': typeof PetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pets/edit': typeof PetsEditRoute
  '/pets/new': typeof PetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pets/edit' | '/pets/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pets/edit' | '/pets/new'
  id: '__root__' | '/' | '/pets/edit' | '/pets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetsEditRoute: typeof PetsEditRoute
  PetsNewRoute: typeof PetsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/edit': {
      id: '/pets/edit'
      path: '/pets/edit'
      fullPath: '/pets/edit'
      preLoaderRoute: typeof PetsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetsEditRoute: PetsEditRoute,
  PetsNewRoute: PetsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
