/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { formOptions } from "@tanstack/react-form"

import { createUserRequestSchema, updateUserRequestSchema } from "./../schema"

import type { CreateUserRequest, UpdateUserRequest } from "./../schema"

export const createUserFormOptions = formOptions({
  defaultValues: {} as CreateUserRequest,
  validators: {
    onSubmitAsync: createUserRequestSchema,
  },
})

export const updateUserFormOptions = formOptions({
  defaultValues: {} as UpdateUserRequest,
  validators: {
    onSubmitAsync: updateUserRequestSchema,
  },
})

