/**
 * OpenAPI operations generation
 * Generates TanStack Query helpers for OpenAPI operations using better-fetch
 */

import { extractOperations } from "./schema";

import type { OpenAPISourceConfig } from "@/core/config";
import type {
  GeneratedFile,
  OpenAPIAdapterSchema,
  OperationGenOptions,
} from "../types";
import type { ParsedOperation } from "./schema";

/**
 * Generate TanStack Query operation helpers from OpenAPI spec
 */
export function generateOpenAPIOperations(
  schema: OpenAPIAdapterSchema,
  _config: OpenAPISourceConfig,
  options: OperationGenOptions,
): GeneratedFile {
  const { document } = schema;
  const operations = extractOperations(document);

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("/* This file is auto-generated by tangen. Do not edit. */");
  lines.push("");

  // Separate operations by type
  const queries = operations.filter((op) => ["get"].includes(op.method));
  const mutations = operations.filter((op) =>
    ["post", "put", "patch", "delete"].includes(op.method),
  );

  // Imports
  const tanstackImports: string[] = [];
  if (queries.length > 0) tanstackImports.push("queryOptions");
  if (mutations.length > 0) tanstackImports.push("mutationOptions");

  if (tanstackImports.length > 0) {
    lines.push(
      `import { ${tanstackImports.join(", ")} } from "@tanstack/react-query"`,
    );
  }

  lines.push(
    `import { $fetch, buildPath, buildQuery } from "${options.clientImportPath}"`,
  );
  lines.push("");

  // Type imports
  const typeImports = generateTypeImports(operations);
  if (typeImports) {
    lines.push("import type {");
    lines.push(typeImports);
    lines.push(`} from "${options.typesImportPath}"`);
    lines.push("");
  }

  // Always include source name in query keys for consistency
  const queryKeyPrefix = `"${options.sourceName}", `;

  // Generate query options for GET operations
  if (queries.length > 0) {
    lines.push("// Query Options (GET operations)");
    lines.push("");
    for (const op of queries) {
      lines.push(generateQueryOption(op, queryKeyPrefix));
      lines.push("");
    }
  }

  // Generate mutation options for POST/PUT/PATCH/DELETE operations
  if (mutations.length > 0) {
    lines.push("// Mutation Options (POST/PUT/PATCH/DELETE operations)");
    lines.push("");
    for (const op of mutations) {
      lines.push(generateMutationOption(op, queryKeyPrefix));
      lines.push("");
    }
  }

  return {
    filename: "operations.ts",
    content: lines.join("\n"),
  };
}

/**
 * Generate type imports for all operations
 */
function generateTypeImports(operations: ParsedOperation[]): string {
  const imports: string[] = [];
  const seen = new Set<string>();

  for (const op of operations) {
    const baseName = toPascalCase(op.operationId);
    const hasParams = op.pathParams.length > 0 || op.queryParams.length > 0;

    // Response type
    if (op.responseSchema) {
      const responseName = `${baseName}Response`;
      if (!seen.has(responseName)) {
        seen.add(responseName);
        imports.push(`\t${responseName},`);
      }
    }

    // Request body type
    if (op.requestBody) {
      const requestName = `${baseName}Request`;
      if (!seen.has(requestName)) {
        seen.add(requestName);
        imports.push(`\t${requestName},`);
      }
    }

    // Params type
    if (hasParams) {
      const paramsName = `${baseName}Params`;
      if (!seen.has(paramsName)) {
        seen.add(paramsName);
        imports.push(`\t${paramsName},`);
      }
    }

    // Zod schemas for runtime validation
    if (op.responseSchema) {
      const schemaName = toSchemaName(`${baseName}Response`);
      if (!seen.has(schemaName)) {
        seen.add(schemaName);
        imports.push(`\t${schemaName},`);
      }
    }
  }

  return imports.join("\n");
}

/**
 * Generate queryOptions for a GET operation
 */
function generateQueryOption(op: ParsedOperation, keyPrefix: string): string {
  const baseName = toPascalCase(op.operationId);
  const fnName = `${toCamelCase(op.operationId)}QueryOptions`;
  const hasPathParams = op.pathParams.length > 0;
  const hasQueryParams = op.queryParams.length > 0;
  const hasParams = hasPathParams || hasQueryParams;
  const hasResponse = !!op.responseSchema;

  const paramsType = hasParams ? `${baseName}Params` : null;
  const responseType = hasResponse ? `${baseName}Response` : "unknown";
  const responseSchema = hasResponse
    ? toSchemaName(`${baseName}Response`)
    : null;

  // Build path expression
  let pathExpr: string;
  if (hasPathParams) {
    const pathParamNames = op.pathParams.map((p) => p.name);
    const pathParamsObj = pathParamNames
      .map((n) => `${n}: params.${n}`)
      .join(", ");
    pathExpr = `buildPath("${op.path}", { ${pathParamsObj} })`;
  } else {
    pathExpr = `"${op.path}"`;
  }

  // Build query string expression
  let queryExpr = "";
  if (hasQueryParams) {
    const queryParamNames = op.queryParams.map((p) => p.name);
    const queryParamsObj = queryParamNames
      .map((n) => `${n}: params.${n}`)
      .join(", ");
    queryExpr = `
		const query = buildQuery({ ${queryParamsObj} })
		const url = query ? \`\${path}?\${query}\` : path`;
  }

  // Build function parameters
  const fnParams = hasParams ? `params: ${paramsType}` : "";

  // Build query key
  const queryKey = hasParams
    ? `[${keyPrefix}"${op.operationId}", params]`
    : `[${keyPrefix}"${op.operationId}"]`;

  // Build fetch options
  const fetchOptions = responseSchema ? `{ output: ${responseSchema} }` : "";

  // Generate the function
  if (hasQueryParams) {
    return `export const ${fnName} = (${fnParams}) =>
	queryOptions({
		queryKey: ${queryKey},
		queryFn: async () => {
			const path = ${pathExpr}${queryExpr}
			const { data, error } = await $fetch<${responseType}>(url${fetchOptions ? `, ${fetchOptions}` : ""})
			if (error) throw error
			return data
		},
	})`;
  }

  if (hasPathParams) {
    return `export const ${fnName} = (${fnParams}) =>
	queryOptions({
		queryKey: ${queryKey},
		queryFn: async () => {
			const path = ${pathExpr}
			const { data, error } = await $fetch<${responseType}>(path${fetchOptions ? `, ${fetchOptions}` : ""})
			if (error) throw error
			return data
		},
	})`;
  }

  return `export const ${fnName} = (${fnParams ? fnParams : ""}) =>
	queryOptions({
		queryKey: ${queryKey},
		queryFn: async () => {
			const { data, error } = await $fetch<${responseType}>(${pathExpr}${fetchOptions ? `, ${fetchOptions}` : ""})
			if (error) throw error
			return data
		},
	})`;
}

/**
 * Generate mutationOptions for POST/PUT/PATCH/DELETE operations
 */
function generateMutationOption(
  op: ParsedOperation,
  keyPrefix: string,
): string {
  const baseName = toPascalCase(op.operationId);
  const fnName = `${toCamelCase(op.operationId)}MutationOptions`;
  const hasPathParams = op.pathParams.length > 0;
  const hasBody = !!op.requestBody;
  const hasResponse = !!op.responseSchema;

  const paramsType = hasPathParams ? `${baseName}Params` : null;
  const requestType = hasBody ? `${baseName}Request` : null;
  const responseType = hasResponse ? `${baseName}Response` : "unknown";
  const responseSchema = hasResponse
    ? toSchemaName(`${baseName}Response`)
    : null;

  // Build path expression
  let pathExpr: string;
  if (hasPathParams) {
    const pathParamNames = op.pathParams.map((p) => p.name);
    const pathParamsObj = pathParamNames
      .map((n) => `${n}: params.${n}`)
      .join(", ");
    pathExpr = `buildPath("${op.path}", { ${pathParamsObj} })`;
  } else {
    pathExpr = `"${op.path}"`;
  }

  // Build mutation key
  const mutationKey = `[${keyPrefix}"${op.operationId}"]`;

  // Build fetch options base
  const fetchOptionsBase: string[] = [`method: "${op.method.toUpperCase()}"`];
  if (responseSchema) {
    fetchOptionsBase.push(`output: ${responseSchema}`);
  }

  // Determine mutationFn variables type
  let variablesType: string;
  if (hasPathParams && hasBody) {
    variablesType = `{ params: ${paramsType}, body: ${requestType} }`;
  } else if (hasPathParams) {
    variablesType = `{ params: ${paramsType} }`;
  } else if (hasBody && requestType) {
    variablesType = requestType;
  } else {
    variablesType = "void";
  }

  // Generate the function body based on params/body combinations
  if (hasPathParams && hasBody) {
    return `export const ${fnName} = () =>
	mutationOptions({
		mutationKey: ${mutationKey},
		mutationFn: async (variables: ${variablesType}) => {
			const path = buildPath("${op.path}", { ${op.pathParams.map((p) => `${p.name}: variables.params.${p.name}`).join(", ")} })
			const { data, error } = await $fetch<${responseType}>(path, {
				${fetchOptionsBase.join(",\n\t\t\t\t")},
				body: variables.body,
			})
			if (error) throw error
			return data
		},
	})`;
  }

  if (hasPathParams) {
    return `export const ${fnName} = () =>
	mutationOptions({
		mutationKey: ${mutationKey},
		mutationFn: async (variables: ${variablesType}) => {
			const path = buildPath("${op.path}", { ${op.pathParams.map((p) => `${p.name}: variables.params.${p.name}`).join(", ")} })
			const { data, error } = await $fetch<${responseType}>(path, {
				${fetchOptionsBase.join(",\n\t\t\t\t")},
			})
			if (error) throw error
			return data
		},
	})`;
  }

  if (hasBody) {
    return `export const ${fnName} = () =>
	mutationOptions({
		mutationKey: ${mutationKey},
		mutationFn: async (body: ${variablesType}) => {
			const { data, error } = await $fetch<${responseType}>(${pathExpr}, {
				${fetchOptionsBase.join(",\n\t\t\t\t")},
				body,
			})
			if (error) throw error
			return data
		},
	})`;
  }

  return `export const ${fnName} = () =>
	mutationOptions({
		mutationKey: ${mutationKey},
		mutationFn: async () => {
			const { data, error } = await $fetch<${responseType}>(${pathExpr}, {
				${fetchOptionsBase.join(",\n\t\t\t\t")},
			})
			if (error) throw error
			return data
		},
	})`;
}

/**
 * Convert a string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

/**
 * Convert a string to camelCase
 */
function toCamelCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toLowerCase());
}

/**
 * Convert a type name to a Zod schema variable name
 */
function toSchemaName(typeName: string): string {
  const camelCase = typeName.charAt(0).toLowerCase() + typeName.slice(1);
  return `${camelCase}Schema`;
}
