/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { infiniteQueryOptions, mutationOptions, queryOptions } from "@tanstack/react-query"

import { createPet, createUser, deletePet, deleteUser, getPet, getUser, listPets, listUsers, updatePet, updateUser } from "../functions"

import type { CreatePetRequest, CreateUserRequest, GetPetParams, GetUserParams, ListPetsParams, ListUsersParams, UpdatePetRequest, UpdateUserRequest } from "./../schema"

// Query Options (GET operations)

export const listPetsQueryOptions = (params?: ListPetsParams) =>
  queryOptions({
  queryKey: ["api", "listPets", params],
  queryFn: () => listPets(params),
})

export const getPetQueryOptions = (params: GetPetParams) =>
  queryOptions({
  queryKey: ["api", "getPet", params],
  queryFn: () => getPet(params),
})

export const listUsersQueryOptions = (params?: ListUsersParams) =>
  queryOptions({
  queryKey: ["api", "listUsers", params],
  queryFn: () => listUsers(params),
})

export const getUserQueryOptions = (params: GetUserParams) =>
  queryOptions({
  queryKey: ["api", "getUser", params],
  queryFn: () => getUser(params),
})

// Infinite Query Options (paginated GET operations)

export const listPetsInfiniteQueryOptions = (params?: Omit<ListPetsParams, "offset">) =>
  infiniteQueryOptions({
  queryKey: ["api", "listPets", "infinite", params],
  queryFn: ({ pageParam }) => listPets({ ...params, offset: pageParam }),
  initialPageParam: 0,
  getNextPageParam: (lastPage, _allPages, lastPageParam) => (lastPageParam ?? 0) + (params?.limit ?? 20) < lastPage.total ? (lastPageParam ?? 0) + (params?.limit ?? 20) : undefined,
})

export const listUsersInfiniteQueryOptions = (params?: Omit<ListUsersParams, "offset">) =>
  infiniteQueryOptions({
  queryKey: ["api", "listUsers", "infinite", params],
  queryFn: ({ pageParam }) => listUsers({ ...params, offset: pageParam }),
  initialPageParam: 0,
  getNextPageParam: (lastPage, _allPages, lastPageParam) => (lastPageParam ?? 0) + (params?.limit ?? 20) < lastPage.total ? (lastPageParam ?? 0) + (params?.limit ?? 20) : undefined,
})

// Mutation Options (POST/PUT/PATCH/DELETE operations)

export const createPetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "createPet"],
  mutationFn: (variables: { body: CreatePetRequest }) => createPet(variables),
})

export const updatePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "updatePet"],
  mutationFn: (variables: { petId: string; body: UpdatePetRequest }) => updatePet(variables),
})

export const deletePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "deletePet"],
  mutationFn: (variables: { petId: string }) => deletePet(variables),
})

export const createUserMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "createUser"],
  mutationFn: (variables: { body: CreateUserRequest }) => createUser(variables),
})

export const updateUserMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "updateUser"],
  mutationFn: (variables: { userId: string; body: UpdateUserRequest }) => updateUser(variables),
})

export const deleteUserMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "deleteUser"],
  mutationFn: (variables: { userId: string }) => deleteUser(variables),
})

