/**
 * OpenAPI operations generation
 *
 * Generates queryOptions and mutationOptions that import standalone
 * fetch functions from functions.ts.
 */

import type { OpenAPISourceConfig } from "@/core/config";
import type {
  GeneratedFile,
  OpenAPIAdapterSchema,
  OperationGenOptions,
} from "../types";
import type { ParsedOperation } from "./schema";

/** Hardcoded import path for functions (always ../functions from query/) */
const FUNCTIONS_IMPORT_PATH = "../functions";

/**
 * Generate TanStack Query operation helpers from OpenAPI spec
 */
export function generateOpenAPIOperations(
  _schema: OpenAPIAdapterSchema,
  _config: OpenAPISourceConfig,
  operations: ParsedOperation[],
  options: OperationGenOptions,
): GeneratedFile {
  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("/* This file is auto-generated by tangrams. Do not edit. */");
  lines.push("");

  // Separate operations by type
  const queries = operations.filter((op) => ["get"].includes(op.method));
  const mutations = operations.filter((op) =>
    ["post", "put", "patch", "delete"].includes(op.method),
  );

  // Imports
  const tanstackImports: string[] = [];
  if (queries.length > 0) tanstackImports.push("queryOptions");
  if (mutations.length > 0) tanstackImports.push("mutationOptions");

  if (tanstackImports.length > 0) {
    lines.push(
      `import { ${tanstackImports.join(", ")} } from "@tanstack/react-query"`,
    );
  }

  // Import functions from functions.ts
  const functionImports = getFunctionImports(operations);
  if (functionImports.length > 0) {
    lines.push(
      `import { ${functionImports.join(", ")} } from "${FUNCTIONS_IMPORT_PATH}"`,
    );
  }
  lines.push("");

  // Type imports (only needed for function signatures)
  const typeImports = generateTypeImports(operations);
  if (typeImports) {
    lines.push("import type {");
    lines.push(typeImports);
    lines.push(`} from "${options.typesImportPath}"`);
    lines.push("");
  }

  // Always include source name in query keys for consistency
  const queryKeyPrefix = `"${options.sourceName}", `;

  // Generate query options for GET operations
  if (queries.length > 0) {
    lines.push("// Query Options (GET operations)");
    lines.push("");
    for (const op of queries) {
      lines.push(generateQueryOption(op, queryKeyPrefix));
      lines.push("");
    }
  }

  // Generate mutation options for POST/PUT/PATCH/DELETE operations
  if (mutations.length > 0) {
    lines.push("// Mutation Options (POST/PUT/PATCH/DELETE operations)");
    lines.push("");
    for (const op of mutations) {
      lines.push(generateMutationOption(op, queryKeyPrefix));
      lines.push("");
    }
  }

  return {
    filename: "operations.ts",
    content: lines.join("\n"),
  };
}

/**
 * Get function import names for all operations
 */
function getFunctionImports(operations: ParsedOperation[]): string[] {
  return operations.map((op) => toCamelCase(op.operationId));
}

/**
 * Generate imports for types
 */
function generateTypeImports(operations: ParsedOperation[]): string {
  const typeImportsList: string[] = [];
  const seenTypes = new Set<string>();

  for (const op of operations) {
    const baseName = toPascalCase(op.operationId);
    const hasParams = op.pathParams.length > 0 || op.queryParams.length > 0;

    // Request body type
    if (op.requestBody) {
      const requestName = `${baseName}Request`;
      if (!seenTypes.has(requestName)) {
        seenTypes.add(requestName);
        typeImportsList.push(`\ttype ${requestName},`);
      }
    }

    // Params type
    if (hasParams) {
      const paramsName = `${baseName}Params`;
      if (!seenTypes.has(paramsName)) {
        seenTypes.add(paramsName);
        typeImportsList.push(`\ttype ${paramsName},`);
      }
    }
  }

  return typeImportsList.join("\n");
}

/**
 * Generate queryOptions for a GET operation
 */
function generateQueryOption(op: ParsedOperation, keyPrefix: string): string {
  const baseName = toPascalCase(op.operationId);
  const optionsFnName = `${toCamelCase(op.operationId)}QueryOptions`;
  const fetchFnName = toCamelCase(op.operationId);
  const hasPathParams = op.pathParams.length > 0;
  const hasQueryParams = op.queryParams.length > 0;
  const hasParams = hasPathParams || hasQueryParams;

  const paramsType = hasParams ? `${baseName}Params` : null;

  // Build query key
  const queryKey = hasParams
    ? `[${keyPrefix}"${op.operationId}", params]`
    : `[${keyPrefix}"${op.operationId}"]`;

  if (!hasParams) {
    return `export const ${optionsFnName} = () =>
	queryOptions({
		queryKey: ${queryKey},
		queryFn: () => ${fetchFnName}(),
	})`;
  }

  // Query params are optional, path params are required
  const paramModifier = hasPathParams ? "" : "?";

  return `export const ${optionsFnName} = (params${paramModifier}: ${paramsType}) =>
	queryOptions({
		queryKey: ${queryKey},
		queryFn: () => ${fetchFnName}(params),
	})`;
}

/**
 * Generate mutationOptions for POST/PUT/PATCH/DELETE operations
 */
function generateMutationOption(
  op: ParsedOperation,
  keyPrefix: string,
): string {
  const baseName = toPascalCase(op.operationId);
  const optionsFnName = `${toCamelCase(op.operationId)}MutationOptions`;
  const fetchFnName = toCamelCase(op.operationId);
  const hasPathParams = op.pathParams.length > 0;
  const hasBody = !!op.requestBody;

  const requestType = hasBody ? `${baseName}Request` : null;

  // Build mutation key
  const mutationKey = `[${keyPrefix}"${op.operationId}"]`;

  // Determine mutationFn variables type
  let variablesType: string;
  if (hasPathParams && hasBody) {
    // Extract path param names for the type
    const pathParamTypes = op.pathParams
      .map((p) => `${p.name}: string`)
      .join("; ");
    variablesType = `{ ${pathParamTypes}; body: ${requestType} }`;
  } else if (hasPathParams) {
    const pathParamTypes = op.pathParams
      .map((p) => `${p.name}: string`)
      .join("; ");
    variablesType = `{ ${pathParamTypes} }`;
  } else if (hasBody && requestType) {
    variablesType = `{ body: ${requestType} }`;
  } else {
    variablesType = "void";
  }

  if (variablesType === "void") {
    return `export const ${optionsFnName} = () =>
	mutationOptions({
		mutationKey: ${mutationKey},
		mutationFn: () => ${fetchFnName}(),
	})`;
  }

  return `export const ${optionsFnName} = () =>
	mutationOptions({
		mutationKey: ${mutationKey},
		mutationFn: (variables: ${variablesType}) => ${fetchFnName}(variables),
	})`;
}

/**
 * Convert a string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

/**
 * Convert a string to camelCase
 */
function toCamelCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toLowerCase());
}
