/**
 * OpenAPI server function generation for TanStack Start
 * Generates createServerFn() wrappers with Zod validation
 */

import { extractOperations } from "./schema";

import type { OpenAPISourceConfig } from "@/core/config";
import type {
  GeneratedFile,
  OpenAPIAdapterSchema,
  StartGenOptions,
} from "../types";
import type { ParsedOperation } from "./schema";

/**
 * Generate TanStack Start server functions from OpenAPI spec
 */
export function generateOpenAPIStart(
  schema: OpenAPIAdapterSchema,
  _config: OpenAPISourceConfig,
  options: StartGenOptions,
): GeneratedFile {
  const { document } = schema;
  const operations = extractOperations(document);

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("/* This file is auto-generated by tangrams. Do not edit. */");
  lines.push("");

  // Imports
  lines.push(`import { createServerFn } from "@tanstack/react-start"`);
  lines.push(
    `import { $fetch, buildPath, buildQuery } from "${options.clientImportPath}"`,
  );
  lines.push("");

  // Type and schema imports
  const { typeImports, schemaImports } = generateImports(operations);
  if (typeImports || schemaImports) {
    const allImports: string[] = [];
    if (typeImports) allImports.push(typeImports);
    if (schemaImports) allImports.push(schemaImports);

    lines.push("import {");
    lines.push(allImports.join("\n"));
    lines.push(`} from "${options.typesImportPath}"`);
    lines.push("");
  }

  // Separate operations by type
  const queries = operations.filter((op) => ["get"].includes(op.method));
  const mutations = operations.filter((op) =>
    ["post", "put", "patch", "delete"].includes(op.method),
  );

  // Generate server functions for GET operations
  if (queries.length > 0) {
    lines.push("// Query Server Functions (GET operations)");
    lines.push("");
    for (const op of queries) {
      lines.push(generateQueryServerFn(op));
      lines.push("");
    }
  }

  // Generate server functions for POST/PUT/PATCH/DELETE operations
  if (mutations.length > 0) {
    lines.push(
      "// Mutation Server Functions (POST/PUT/PATCH/DELETE operations)",
    );
    lines.push("");
    for (const op of mutations) {
      lines.push(generateMutationServerFn(op));
      lines.push("");
    }
  }

  return {
    filename: "functions.ts",
    content: lines.join("\n"),
  };
}

/**
 * Generate imports for types and schemas
 */
function generateImports(operations: ParsedOperation[]): {
  typeImports: string;
  schemaImports: string;
} {
  const typeImportsList: string[] = [];
  const schemaImportsList: string[] = [];
  const seenTypes = new Set<string>();
  const seenSchemas = new Set<string>();

  for (const op of operations) {
    const baseName = toPascalCase(op.operationId);
    const hasParams = op.pathParams.length > 0 || op.queryParams.length > 0;

    // Response type and schema
    if (op.responseSchema) {
      const responseName = `${baseName}Response`;
      if (!seenTypes.has(responseName)) {
        seenTypes.add(responseName);
        typeImportsList.push(`\ttype ${responseName},`);
      }
      const schemaName = toSchemaName(`${baseName}Response`);
      if (!seenSchemas.has(schemaName)) {
        seenSchemas.add(schemaName);
        schemaImportsList.push(`\t${schemaName},`);
      }
    }

    // Request body type and schema
    if (op.requestBody) {
      const requestName = `${baseName}Request`;
      if (!seenTypes.has(requestName)) {
        seenTypes.add(requestName);
        typeImportsList.push(`\ttype ${requestName},`);
      }
      const schemaName = toSchemaName(`${baseName}Request`);
      if (!seenSchemas.has(schemaName)) {
        seenSchemas.add(schemaName);
        schemaImportsList.push(`\t${schemaName},`);
      }
    }

    // Params type and schema
    if (hasParams) {
      const paramsName = `${baseName}Params`;
      if (!seenTypes.has(paramsName)) {
        seenTypes.add(paramsName);
        typeImportsList.push(`\ttype ${paramsName},`);
      }
      const schemaName = toSchemaName(`${baseName}Params`);
      if (!seenSchemas.has(schemaName)) {
        seenSchemas.add(schemaName);
        schemaImportsList.push(`\t${schemaName},`);
      }
    }
  }

  return {
    typeImports: typeImportsList.join("\n"),
    schemaImports: schemaImportsList.join("\n"),
  };
}

/**
 * Generate server function for a GET operation
 */
function generateQueryServerFn(op: ParsedOperation): string {
  const baseName = toPascalCase(op.operationId);
  const fnName = `${toCamelCase(op.operationId)}Fn`;
  const hasPathParams = op.pathParams.length > 0;
  const hasQueryParams = op.queryParams.length > 0;
  const hasParams = hasPathParams || hasQueryParams;
  const hasResponse = !!op.responseSchema;

  const paramsSchema = hasParams ? toSchemaName(`${baseName}Params`) : null;
  const responseType = hasResponse ? `${baseName}Response` : "unknown";
  const responseSchema = hasResponse
    ? toSchemaName(`${baseName}Response`)
    : null;

  // Build the fetch body
  const fetchBody = generateFetchBody(op, responseType, responseSchema, "data");

  if (!hasParams) {
    return `export const ${fnName} = createServerFn({ method: "GET" })
	.handler(async () => {
${fetchBody}
	})`;
  }

  return `export const ${fnName} = createServerFn({ method: "GET" })
	.inputValidator(${paramsSchema})
	.handler(async ({ data }) => {
${fetchBody}
	})`;
}

/**
 * Generate server function for a mutation operation
 */
function generateMutationServerFn(op: ParsedOperation): string {
  const baseName = toPascalCase(op.operationId);
  const fnName = `${toCamelCase(op.operationId)}Fn`;
  const hasPathParams = op.pathParams.length > 0;
  const hasBody = !!op.requestBody;
  const hasResponse = !!op.responseSchema;

  const responseType = hasResponse ? `${baseName}Response` : "unknown";
  const responseSchema = hasResponse
    ? toSchemaName(`${baseName}Response`)
    : null;

  // Build the fetch body
  const fetchBody = generateMutationFetchBody(
    op,
    responseType,
    responseSchema,
    "data",
  );

  // Determine validator schema based on what params we have
  let validatorSchema: string;
  if (hasPathParams && hasBody) {
    // Use type-only validation for combined params + body
    validatorSchema = `(data: { params: ${baseName}Params, body: ${baseName}Request }) => data`;
  } else if (hasPathParams) {
    // Use type-only validation for params object wrapper
    validatorSchema = `(data: { params: ${baseName}Params }) => data`;
  } else if (hasBody) {
    // Use Zod schema for request body validation
    validatorSchema = toSchemaName(`${baseName}Request`);
  } else {
    // No params or body
    return `export const ${fnName} = createServerFn({ method: "POST" })
	.handler(async () => {
${fetchBody}
	})`;
  }

  return `export const ${fnName} = createServerFn({ method: "POST" })
	.inputValidator(${validatorSchema})
	.handler(async ({ data }) => {
${fetchBody}
	})`;
}

/**
 * Generate fetch body for query server functions
 */
function generateFetchBody(
  op: ParsedOperation,
  responseType: string,
  responseSchema: string | null,
  dataVar: string,
): string {
  const hasPathParams = op.pathParams.length > 0;
  const hasQueryParams = op.queryParams.length > 0;
  const fetchOptions = responseSchema ? `, { output: ${responseSchema} }` : "";

  const lines: string[] = [];

  if (hasPathParams) {
    const pathParamsObj = op.pathParams
      .map((p) => `${p.name}: ${dataVar}.${p.name}`)
      .join(", ");
    lines.push(
      `\t\tconst path = buildPath("${op.path}", { ${pathParamsObj} })`,
    );
  } else {
    lines.push(`\t\tconst path = "${op.path}"`);
  }

  if (hasQueryParams) {
    const queryParamsObj = op.queryParams
      .map((p) => `${p.name}: ${dataVar}.${p.name}`)
      .join(", ");
    lines.push(`\t\tconst query = buildQuery({ ${queryParamsObj} })`);
    lines.push(`\t\tconst url = query ? \`\${path}?\${query}\` : path`);
    lines.push(
      `\t\tconst { data: result, error } = await $fetch<${responseType}>(url${fetchOptions})`,
    );
  } else {
    lines.push(
      `\t\tconst { data: result, error } = await $fetch<${responseType}>(path${fetchOptions})`,
    );
  }

  lines.push(`\t\tif (error) throw error`);
  lines.push(`\t\treturn result`);

  return lines.join("\n");
}

/**
 * Generate fetch body for mutation server functions
 */
function generateMutationFetchBody(
  op: ParsedOperation,
  responseType: string,
  responseSchema: string | null,
  dataVar: string,
): string {
  const hasPathParams = op.pathParams.length > 0;
  const hasBody = !!op.requestBody;

  const fetchOptionsBase: string[] = [`method: "${op.method.toUpperCase()}"`];
  if (responseSchema) {
    fetchOptionsBase.push(`output: ${responseSchema}`);
  }

  const lines: string[] = [];

  if (hasPathParams) {
    const pathParamsObj = op.pathParams
      .map((p) => `${p.name}: ${dataVar}.params.${p.name}`)
      .join(", ");
    lines.push(
      `\t\tconst path = buildPath("${op.path}", { ${pathParamsObj} })`,
    );
  } else {
    lines.push(`\t\tconst path = "${op.path}"`);
  }

  if (hasBody) {
    const bodyExpr = hasPathParams ? `${dataVar}.body` : dataVar;
    fetchOptionsBase.push(`body: ${bodyExpr}`);
  }

  lines.push(
    `\t\tconst { data: result, error } = await $fetch<${responseType}>(path, {`,
  );
  lines.push(`\t\t\t${fetchOptionsBase.join(",\n\t\t\t")},`);
  lines.push(`\t\t})`);
  lines.push(`\t\tif (error) throw error`);
  lines.push(`\t\treturn result`);

  return lines.join("\n");
}

/**
 * Convert a string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toUpperCase());
}

/**
 * Convert a string to camelCase
 */
function toCamelCase(str: string): string {
  return str
    .replace(/[-_](.)/g, (_, c) => c.toUpperCase())
    .replace(/^(.)/, (_, c) => c.toLowerCase());
}

/**
 * Convert a type name to a Zod schema variable name
 */
function toSchemaName(typeName: string): string {
  const camelCase = typeName.charAt(0).toLowerCase() + typeName.slice(1);
  return `${camelCase}Schema`;
}

/**
 * Get the list of exported server function names for a set of operations
 * Used by operations.ts to generate imports when serverFunctions: true
 */
export function getOpenAPIServerFunctionNames(
  operations: ParsedOperation[],
): string[] {
  return operations.map((op) => `${toCamelCase(op.operationId)}Fn`);
}
