/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { formOptions } from "@tanstack/react-form"

import { createPetMutationVariablesSchema, deletePetMutationVariablesSchema, updatePetMutationVariablesSchema } from "./../schema"

import type { CreatePetMutationVariables, DeletePetMutationVariables, UpdatePetMutationVariables } from "./../schema"

export const createPetFormOptions = formOptions({
  defaultValues: {} as CreatePetMutationVariables,
  validators: {
    onSubmitAsync: createPetMutationVariablesSchema,
  },
})

export const updatePetFormOptions = formOptions({
  defaultValues: {} as UpdatePetMutationVariables,
  validators: {
    onSubmitAsync: updatePetMutationVariablesSchema,
  },
})

export const deletePetFormOptions = formOptions({
  defaultValues: {} as DeletePetMutationVariables,
  validators: {
    onSubmitAsync: deletePetMutationVariablesSchema,
  },
})

