/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { infiniteQueryOptions, mutationOptions, queryOptions } from "@tanstack/react-query"

import { createUser, deleteUser, getUser, listUsers, updateUser } from "../functions"

import type { CreateUserRequest, GetUserParams, ListUsersParams, UpdateUserRequest } from "./../schema"

// Query Options (GET operations)

export const listUsersQueryOptions = (params?: ListUsersParams) =>
  queryOptions({
  queryKey: ["users", "listUsers", params],
  queryFn: () => listUsers(params),
})

export const getUserQueryOptions = (params: GetUserParams) =>
  queryOptions({
  queryKey: ["users", "getUser", params],
  queryFn: () => getUser(params),
})

// Infinite Query Options (paginated GET operations)

export const listUsersInfiniteQueryOptions = (params?: Omit<ListUsersParams, "offset">) =>
  infiniteQueryOptions({
  queryKey: ["users", "listUsers", "infinite", params],
  queryFn: ({ pageParam }) => listUsers({ ...params, offset: pageParam }),
  initialPageParam: 0,
  getNextPageParam: (lastPage, _allPages, lastPageParam) => (lastPageParam ?? 0) + (params?.limit ?? 20) < lastPage.total ? (lastPageParam ?? 0) + (params?.limit ?? 20) : undefined,
})

// Mutation Options (POST/PUT/PATCH/DELETE operations)

export const createUserMutationOptions = () =>
  mutationOptions({
  mutationKey: ["users", "createUser"],
  mutationFn: (variables: { body: CreateUserRequest }) => createUser(variables),
})

export const updateUserMutationOptions = () =>
  mutationOptions({
  mutationKey: ["users", "updateUser"],
  mutationFn: (variables: { userId: string; body: UpdateUserRequest }) => updateUser(variables),
})

export const deleteUserMutationOptions = () =>
  mutationOptions({
  mutationKey: ["users", "deleteUser"],
  mutationFn: (variables: { userId: string }) => deleteUser(variables),
})

