export interface ClientGeneratorOptions {
  url: string;
  headers?: Record<string, string>;
}

/**
 * Generate the GraphQL client file
 */
export function generateClient(options: ClientGeneratorOptions): string {
  const { url, headers } = options;

  const headerEntries = headers ? Object.entries(headers) : [];
  const headersBlock =
    headerEntries.length > 0
      ? headerEntries
          .map(([key, value]) => `\t\t"${key}": "${value}",`)
          .join("\n")
      : "";

  return `/* eslint-disable */
/* This file is auto-generated by tangen. Do not edit. */

import { GraphQLClient } from "graphql-request"

const endpoint = "${url}"

export const client = new GraphQLClient(endpoint, {
	headers: {
${headersBlock}
		// Add your runtime headers here
		// Authorization: \`Bearer \${token}\`,
	},
})

/**
 * Update the client headers at runtime
 */
export const setClientHeaders = (headers: HeadersInit) => {
	client.setHeaders(headers)
}

/**
 * Create a new client instance with custom headers
 */
export const getClient = (headers?: HeadersInit) => {
	return new GraphQLClient(endpoint, { headers })
}
`;
}
