import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { loadDocuments } from "../core/documents";
import { generateOperations } from "./operations";

const fixturesDir = resolve(__dirname, "../test/fixtures/graphql");

describe("generateOperations", () => {
  it("generates operations file with eslint-disable comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("/* eslint-disable */");
  });

  it("generates operations file with auto-generated comment", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("auto-generated by tangen");
  });

  it("imports queryOptions and mutationOptions from @tanstack/react-query", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain(
      'import { mutationOptions, queryOptions } from "@tanstack/react-query"',
    );
  });

  it("imports getClient from the specified client path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./custom-client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain('import { getClient } from "./custom-client"');
  });

  it("imports types from the specified types path", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./custom-types",
      sourceName: "test",
    });

    expect(result).toContain('} from "./custom-types"');
  });

  it("generates fragment document constants", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("const UserFieldsFragmentDoc");
  });

  it("generates operation document constants", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("const GetUserDocument");
    expect(result).toContain("const ListUsersDocument");
    expect(result).toContain("const CreateUserDocument");
  });

  it("generates queryOptions for query operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("export const getUserQueryOptions");
    expect(result).toContain("export const listUsersQueryOptions");
  });

  it("generates mutation options for mutation operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain("export const createUserMutationOptions");
    expect(result).toContain("export const updateUserMutationOptions");
    expect(result).toContain("export const deleteUserMutationOptions");
  });

  it("includes queryKey for query operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain('queryKey: ["test", "GetUser"');
    expect(result).toContain('queryKey: ["test", "ListUsers"');
  });

  it("includes mutationKey for mutation operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain('mutationKey: ["test", "CreateUser"]');
    expect(result).toContain('mutationKey: ["test", "UpdateUser"]');
  });

  it("handles operations with required variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    // GetUser has required $id variable
    expect(result).toContain(
      "getUserQueryOptions = (variables: GetUserQueryVariables)",
    );
  });

  it("handles operations with optional variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    // ListUsers has all optional variables
    expect(result).toContain(
      "listUsersQueryOptions = (variables?: ListUsersQueryVariables)",
    );
  });

  it("concatenates fragment documents in operation documents", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    // Operations using UserFields fragment should concatenate the fragment
    expect(result).toContain("+ UserFieldsFragmentDoc");
  });

  it("matches snapshot for user operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/user.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });

  it("matches snapshot for post operations with nested fragments", async () => {
    const documents = await loadDocuments([
      `${fixturesDir}/user.graphql`,
      `${fixturesDir}/post.graphql`,
    ]);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });

  it("only imports queryOptions when there are no mutations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain(
      'import { queryOptions } from "@tanstack/react-query"',
    );
    expect(result).not.toContain("mutationOptions");
  });

  it("only imports mutationOptions when there are no queries", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toContain(
      'import { mutationOptions } from "@tanstack/react-query"',
    );
    expect(result).not.toContain("queryOptions");
  });

  it("does not import variables types for operations without variables", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    // GetAllUsers has no variables, so no variables type should be imported
    expect(result).not.toContain("GetAllUsersQueryVariables");
    // But GetUserById does have variables
    expect(result).toContain("GetUserByIdQueryVariables");
  });

  it("matches snapshot for query-only operations", async () => {
    const documents = await loadDocuments(`${fixturesDir}/query-only.graphql`);
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });

  it("matches snapshot for mutation-only operations", async () => {
    const documents = await loadDocuments(
      `${fixturesDir}/mutation-only.graphql`,
    );
    const result = generateOperations({
      documents,
      clientImportPath: "./client",
      typesImportPath: "./types",
      sourceName: "test",
    });

    expect(result).toMatchSnapshot();
  });
});
