import { getFragmentDependencies } from "../core/documents";
import {
  toDocumentName,
  toFragmentDocName,
  toMutationOptionsName,
  toMutationTypeName,
  toMutationVariablesTypeName,
  toQueryOptionsName,
  toQueryTypeName,
  toQueryVariablesTypeName,
} from "../utils/naming";

import type {
  ParsedDocuments,
  ParsedFragment,
  ParsedOperation,
} from "../core/documents";

export interface OperationsGeneratorOptions {
  documents: ParsedDocuments;
  clientImportPath: string;
  typesImportPath: string;
}

/**
 * Generate the operations file with queryOptions and mutationOptions
 */
export function generateOperations(
  options: OperationsGeneratorOptions,
): string {
  const { documents, clientImportPath, typesImportPath } = options;
  const { operations, fragments } = documents;

  const lines: string[] = [];
  lines.push("/* eslint-disable */");
  lines.push("/* This file is auto-generated by tangen. Do not edit. */");
  lines.push("");

  // Imports
  lines.push('import { queryOptions } from "@tanstack/react-query"');
  lines.push(`import { client } from "${clientImportPath}"`);
  lines.push("");

  // Type imports
  const typeImports = generateTypeImports(operations);
  if (typeImports) {
    lines.push("import type {");
    lines.push(typeImports);
    lines.push(`} from "${typesImportPath}"`);
    lines.push("");
  }

  // Fragment documents
  if (fragments.length > 0) {
    lines.push("// Fragment Documents");
    for (const fragment of fragments) {
      lines.push(generateFragmentDocument(fragment));
      lines.push("");
    }
  }

  // Operation documents and options
  lines.push("// Documents & Operations");
  for (const operation of operations) {
    const fragmentDeps = getFragmentDependencies(operation, fragments);
    lines.push(generateOperationDocument(operation, fragmentDeps));
    lines.push("");

    if (operation.operation === "query") {
      lines.push(generateQueryOptions(operation));
    } else {
      lines.push(generateMutationOptions(operation));
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate type imports for all operations
 */
function generateTypeImports(operations: ParsedOperation[]): string {
  const imports: string[] = [];

  for (const op of operations) {
    if (op.operation === "query") {
      imports.push(`\t${toQueryTypeName(op.name)},`);
      imports.push(`\t${toQueryVariablesTypeName(op.name)},`);
    } else {
      imports.push(`\t${toMutationTypeName(op.name)},`);
      imports.push(`\t${toMutationVariablesTypeName(op.name)},`);
    }
  }

  return imports.join("\n");
}

/**
 * Generate a fragment document constant
 */
function generateFragmentDocument(fragment: ParsedFragment): string {
  const docName = toFragmentDocName(fragment.name);
  return `const ${docName} = /* GraphQL */ \`
${fragment.document}
\``;
}

/**
 * Generate an operation document constant with fragment dependencies
 */
function generateOperationDocument(
  operation: ParsedOperation,
  fragmentDeps: ParsedFragment[],
): string {
  const docName = toDocumentName(operation.name);

  if (fragmentDeps.length === 0) {
    return `const ${docName} = /* GraphQL */ \`
${operation.document}
\``;
  }

  // Build the document with fragment concatenation
  const fragmentConcats = fragmentDeps
    .map((f) => toFragmentDocName(f.name))
    .join(" + ");

  return `const ${docName} = /* GraphQL */ \`
${operation.document}
\` + ${fragmentConcats}`;
}

/**
 * Generate queryOptions for a query operation
 */
function generateQueryOptions(operation: ParsedOperation): string {
  const fnName = toQueryOptionsName(operation.name);
  const docName = toDocumentName(operation.name);
  const queryType = toQueryTypeName(operation.name);
  const variablesType = toQueryVariablesTypeName(operation.name);

  const hasVariables =
    operation.node.variableDefinitions &&
    operation.node.variableDefinitions.length > 0;

  // Check if all variables are optional
  const allOptional =
    hasVariables &&
    operation.node.variableDefinitions?.every(
      (v) => v.type.kind !== "NonNullType",
    );

  if (!hasVariables) {
    return `export const ${fnName} = () =>
	queryOptions({
		queryKey: ["${operation.name}"],
		queryFn: () => client.request<${queryType}>(${docName}),
	})`;
  }

  const variableParam = allOptional
    ? `variables?: ${variablesType}`
    : `variables: ${variablesType}`;

  return `export const ${fnName} = (${variableParam}) =>
	queryOptions({
		queryKey: ["${operation.name}", variables],
		queryFn: () => client.request<${queryType}>(${docName}, variables ?? undefined),
	})`;
}

/**
 * Generate mutation options for a mutation operation
 */
function generateMutationOptions(operation: ParsedOperation): string {
  const fnName = toMutationOptionsName(operation.name);
  const docName = toDocumentName(operation.name);
  const mutationType = toMutationTypeName(operation.name);
  const variablesType = toMutationVariablesTypeName(operation.name);

  const hasVariables =
    operation.node.variableDefinitions &&
    operation.node.variableDefinitions.length > 0;

  if (!hasVariables) {
    return `export const ${fnName} = () => ({
	mutationKey: ["${operation.name}"],
	mutationFn: () => client.request<${mutationType}>(${docName}),
})`;
  }

  return `export const ${fnName} = () => ({
	mutationKey: ["${operation.name}"],
	mutationFn: (variables: ${variablesType}) =>
		client.request<${mutationType}>(${docName}, variables),
})`;
}
