/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as UsersNewRouteImport } from './routes/users/new'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as PetsPetIdIndexRouteImport } from './routes/pets/$petId/index'
import { Route as UsersUserIdEditRouteImport } from './routes/users/$userId/edit'
import { Route as PetsPetIdEditRouteImport } from './routes/pets/$petId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdIndexRoute = PetsPetIdIndexRouteImport.update({
  id: '/pets/$petId/',
  path: '/pets/$petId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdEditRoute = PetsPetIdEditRouteImport.update({
  id: '/pets/$petId/edit',
  path: '/pets/$petId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pets/new': typeof PetsNewRoute
  '/users/new': typeof UsersNewRoute
  '/pets': typeof PetsIndexRoute
  '/users': typeof UsersIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/pets/$petId': typeof PetsPetIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pets/new': typeof PetsNewRoute
  '/users/new': typeof UsersNewRoute
  '/pets': typeof PetsIndexRoute
  '/users': typeof UsersIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/pets/$petId': typeof PetsPetIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pets/new': typeof PetsNewRoute
  '/users/new': typeof UsersNewRoute
  '/pets/': typeof PetsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
  '/pets/$petId/': typeof PetsPetIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pets/new'
    | '/users/new'
    | '/pets'
    | '/users'
    | '/pets/$petId/edit'
    | '/users/$userId/edit'
    | '/pets/$petId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pets/new'
    | '/users/new'
    | '/pets'
    | '/users'
    | '/pets/$petId/edit'
    | '/users/$userId/edit'
    | '/pets/$petId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/pets/new'
    | '/users/new'
    | '/pets/'
    | '/users/'
    | '/pets/$petId/edit'
    | '/users/$userId/edit'
    | '/pets/$petId/'
    | '/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetsNewRoute: typeof PetsNewRoute
  UsersNewRoute: typeof UsersNewRoute
  PetsIndexRoute: typeof PetsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PetsPetIdEditRoute: typeof PetsPetIdEditRoute
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
  PetsPetIdIndexRoute: typeof PetsPetIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/new': {
      id: '/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId/': {
      id: '/pets/$petId/'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId/edit': {
      id: '/pets/$petId/edit'
      path: '/pets/$petId/edit'
      fullPath: '/pets/$petId/edit'
      preLoaderRoute: typeof PetsPetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetsNewRoute: PetsNewRoute,
  UsersNewRoute: UsersNewRoute,
  PetsIndexRoute: PetsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PetsPetIdEditRoute: PetsPetIdEditRoute,
  UsersUserIdEditRoute: UsersUserIdEditRoute,
  PetsPetIdIndexRoute: PetsPetIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
