/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { getClient } from "./client"

import type { CreatePetMutation, CreatePetMutationVariables, DeletePetMutation, DeletePetMutationVariables, GetPetByIdQuery, GetPetByIdQueryVariables, GetPetsQuery, GetPetsQueryVariables, UpdatePetMutation, UpdatePetMutationVariables } from "./schema"

// Fragment Documents
const PetFieldsFragmentDoc = /* GraphQL */ `
fragment PetFields on Pet {
  id
  name
  status
  category
  tags
  photoUrl
  createdAt
  updatedAt
}
`

// Documents
const GetPetsDocument = /* GraphQL */ `
query GetPets(
  $status: PetStatus
  $category: PetCategory
  $limit: Int
  $offset: Int
) {
  pets(status: $status, category: $category, limit: $limit, offset: $offset) {
    data {
      ...PetFields
    }
    total
  }
}
${PetFieldsFragmentDoc}`

const GetPetByIdDocument = /* GraphQL */ `
query GetPetById($id: ID!) {
  pet(id: $id) {
    ...PetFields
  }
}
${PetFieldsFragmentDoc}`

const CreatePetDocument = /* GraphQL */ `
mutation CreatePet($input: CreatePetInput!) {
  createPet(input: $input) {
    ...PetFields
  }
}
${PetFieldsFragmentDoc}`

const UpdatePetDocument = /* GraphQL */ `
mutation UpdatePet($id: ID!, $input: UpdatePetInput!) {
  updatePet(id: $id, input: $input) {
    ...PetFields
  }
}
${PetFieldsFragmentDoc}`

const DeletePetDocument = /* GraphQL */ `
mutation DeletePet($id: ID!) {
  deletePet(id: $id)
}
`

// Functions
export const getPets = async (variables?: GetPetsQueryVariables) =>
  (await getClient()).request<GetPetsQuery>(GetPetsDocument, variables ?? undefined)

export const getPetById = async (variables: GetPetByIdQueryVariables) =>
  (await getClient()).request<GetPetByIdQuery>(GetPetByIdDocument, variables ?? undefined)

export const createPet = async (variables: CreatePetMutationVariables) =>
  (await getClient()).request<CreatePetMutation>(CreatePetDocument, variables)

export const updatePet = async (variables: UpdatePetMutationVariables) =>
  (await getClient()).request<UpdatePetMutation>(UpdatePetDocument, variables)

export const deletePet = async (variables: DeletePetMutationVariables) =>
  (await getClient()).request<DeletePetMutation>(DeletePetDocument, variables)

