/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as PetsNewRouteImport } from './routes/pets/new'
import { Route as PetsPetIdIndexRouteImport } from './routes/pets/$petId/index'
import { Route as PetsPetIdEditRouteImport } from './routes/pets/$petId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsNewRoute = PetsNewRouteImport.update({
  id: '/pets/new',
  path: '/pets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdIndexRoute = PetsPetIdIndexRouteImport.update({
  id: '/pets/$petId/',
  path: '/pets/$petId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsPetIdEditRoute = PetsPetIdEditRouteImport.update({
  id: '/pets/$petId/edit',
  path: '/pets/$petId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pets/new': typeof PetsNewRoute
  '/pets': typeof PetsIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/pets/$petId': typeof PetsPetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pets/new': typeof PetsNewRoute
  '/pets': typeof PetsIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/pets/$petId': typeof PetsPetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pets/new': typeof PetsNewRoute
  '/pets/': typeof PetsIndexRoute
  '/pets/$petId/edit': typeof PetsPetIdEditRoute
  '/pets/$petId/': typeof PetsPetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pets/new' | '/pets' | '/pets/$petId/edit' | '/pets/$petId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pets/new' | '/pets' | '/pets/$petId/edit' | '/pets/$petId'
  id:
    | '__root__'
    | '/'
    | '/pets/new'
    | '/pets/'
    | '/pets/$petId/edit'
    | '/pets/$petId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetsNewRoute: typeof PetsNewRoute
  PetsIndexRoute: typeof PetsIndexRoute
  PetsPetIdEditRoute: typeof PetsPetIdEditRoute
  PetsPetIdIndexRoute: typeof PetsPetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/new': {
      id: '/pets/new'
      path: '/pets/new'
      fullPath: '/pets/new'
      preLoaderRoute: typeof PetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId/': {
      id: '/pets/$petId/'
      path: '/pets/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/$petId/edit': {
      id: '/pets/$petId/edit'
      path: '/pets/$petId/edit'
      fullPath: '/pets/$petId/edit'
      preLoaderRoute: typeof PetsPetIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetsNewRoute: PetsNewRoute,
  PetsIndexRoute: PetsIndexRoute,
  PetsPetIdEditRoute: PetsPetIdEditRoute,
  PetsPetIdIndexRoute: PetsPetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
