/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { infiniteQueryOptions, mutationOptions, queryOptions } from "@tanstack/react-query"

import { createPet, deletePet, getPet, listPets, updatePet } from "../functions"

import type { CreatePetRequest, GetPetParams, ListPetsParams, UpdatePetRequest } from "../schema"

// Query Options (GET operations)

export const listPetsQueryOptions = (params?: ListPetsParams) =>
  queryOptions({
  queryKey: ["api", "listPets", params],
  queryFn: () => listPets(params),
})

export const getPetQueryOptions = (params: GetPetParams) =>
  queryOptions({
  queryKey: ["api", "getPet", params],
  queryFn: () => getPet(params),
})

// Infinite Query Options (paginated GET operations)

export const listPetsInfiniteQueryOptions = (params?: Omit<ListPetsParams, "offset">) =>
  infiniteQueryOptions({
  queryKey: ["api", "listPets", "infinite", params],
  queryFn: ({ pageParam }) => listPets({ ...params, offset: pageParam }),
  initialPageParam: 0,
  getNextPageParam: (lastPage, _allPages, lastPageParam) => (lastPageParam ?? 0) + (params?.limit ?? 20) < lastPage.total ? (lastPageParam ?? 0) + (params?.limit ?? 20) : undefined,
})

// Mutation Options (POST/PUT/PATCH/DELETE operations)

export const createPetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "createPet"],
  mutationFn: (variables: { body: CreatePetRequest }) => createPet(variables),
})

export const updatePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "updatePet"],
  mutationFn: (variables: { petId: string; body: UpdatePetRequest }) => updatePet(variables),
})

export const deletePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "deletePet"],
  mutationFn: (variables: { petId: string }) => deletePet(variables),
})

