/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { getClient, buildPath, buildQuery } from "./client"

import { createUserResponseSchema, getUserResponseSchema, listUsersResponseSchema, updateUserResponseSchema } from "./schema"

import type { CreateUserRequest, CreateUserResponse, GetUserParams, GetUserResponse, ListUsersParams, ListUsersResponse, UpdateUserRequest, UpdateUserResponse } from "./schema"

// Query Functions (GET operations)
export const listUsers = async (params?: ListUsersParams) => {
  const $fetch = await getClient()
  const path = "/users"
  const query = buildQuery({ role: params?.role, limit: params?.limit, offset: params?.offset })
  const url = query ? `${path}?${query}` : path
  const { data, error } = await $fetch<ListUsersResponse>(url, { output: listUsersResponseSchema })
  if (error) throw error
  return data
}

export const getUser = async (params: GetUserParams) => {
  const $fetch = await getClient()
  const path = buildPath("/users/{userId}", { userId: params.userId })
  const { data, error } = await $fetch<GetUserResponse>(path, { output: getUserResponseSchema })
  if (error) throw error
  return data
}

// Mutation Functions (POST/PUT/PATCH/DELETE operations)
export const createUser = async ({ body }: { body: CreateUserRequest }) => {
  const $fetch = await getClient()
  const { data, error } = await $fetch<CreateUserResponse>("/users", {
    method: "POST",
    output: createUserResponseSchema,
    body,
  })
  if (error) throw error
  return data
}

export const updateUser = async ({ userId, body }: { userId: string; body: UpdateUserRequest }) => {
  const $fetch = await getClient()
  const path = buildPath("/users/{userId}", { userId })
  const { data, error } = await $fetch<UpdateUserResponse>(path, {
    method: "PUT",
    output: updateUserResponseSchema,
    body,
  })
  if (error) throw error
  return data
}

export const deleteUser = async ({ userId }: { userId: string }) => {
  const $fetch = await getClient()
  const path = buildPath("/users/{userId}", { userId })
  const { data, error } = await $fetch<unknown>(path, {
    method: "DELETE",
  })
  if (error) throw error
  return data
}

