/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import * as z from "zod"

// Zod Schemas
export const userRoleSchema = z.enum(["admin", "user", "guest"])

export const userSchema = z.object({
  id: z.string(),
  email: z.email(),
  name: z.string(),
  role: userRoleSchema,
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime()
})

export const createUserInputSchema = z.object({
  email: z.email(),
  name: z.string(),
  role: userRoleSchema
})

export const updateUserInputSchema = z.object({
  email: z.email().nullish(),
  name: z.string().nullish(),
  role: userRoleSchema.nullish()
})

export const listUsersResponseSchema = z.object({
  data: z.array(userSchema),
  total: z.number().int()
})

export const listUsersParamsSchema = z.object({
  role: userRoleSchema.nullish(),
  limit: z.number().int().nullish(),
  offset: z.number().int().nullish()
})

export const createUserRequestSchema = createUserInputSchema

export const createUserResponseSchema = userSchema

export const getUserResponseSchema = userSchema

export const getUserParamsSchema = z.object({
  userId: z.string()
})

export const updateUserRequestSchema = updateUserInputSchema

export const updateUserResponseSchema = userSchema

export const updateUserParamsSchema = z.object({
  userId: z.string()
})

export const deleteUserParamsSchema = z.object({
  userId: z.string()
})

// TypeScript Types (inferred from Zod schemas)
export type UserRole = z.infer<typeof userRoleSchema>
export type User = z.infer<typeof userSchema>
export type CreateUserInput = z.infer<typeof createUserInputSchema>
export type UpdateUserInput = z.infer<typeof updateUserInputSchema>
export type ListUsersResponse = z.infer<typeof listUsersResponseSchema>
export type ListUsersParams = z.infer<typeof listUsersParamsSchema>
export type CreateUserRequest = z.infer<typeof createUserRequestSchema>
export type CreateUserResponse = z.infer<typeof createUserResponseSchema>
export type GetUserResponse = z.infer<typeof getUserResponseSchema>
export type GetUserParams = z.infer<typeof getUserParamsSchema>
export type UpdateUserRequest = z.infer<typeof updateUserRequestSchema>
export type UpdateUserResponse = z.infer<typeof updateUserResponseSchema>
export type UpdateUserParams = z.infer<typeof updateUserParamsSchema>
export type DeleteUserParams = z.infer<typeof deleteUserParamsSchema>
