/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { getClient, buildPath, buildQuery } from "./client"

import { createPetResponseSchema, getPetResponseSchema, listPetsResponseSchema, updatePetResponseSchema } from "./schema"

import type { CreatePetRequest, CreatePetResponse, GetPetParams, GetPetResponse, ListPetsParams, ListPetsResponse, UpdatePetRequest, UpdatePetResponse } from "./schema"

// Query Functions (GET operations)
export const listPets = async (params?: ListPetsParams) => {
  const $fetch = await getClient()
  const path = "/pets"
  const query = buildQuery({ status: params?.status, category: params?.category, limit: params?.limit, offset: params?.offset })
  const url = query ? `${path}?${query}` : path
  const { data, error } = await $fetch<ListPetsResponse>(url, { output: listPetsResponseSchema })
  if (error) throw error
  return data
}

export const getPet = async (params: GetPetParams) => {
  const $fetch = await getClient()
  const path = buildPath("/pets/{petId}", { petId: params.petId })
  const { data, error } = await $fetch<GetPetResponse>(path, { output: getPetResponseSchema })
  if (error) throw error
  return data
}

// Mutation Functions (POST/PUT/PATCH/DELETE operations)
export const createPet = async ({ body }: { body: CreatePetRequest }) => {
  const $fetch = await getClient()
  const { data, error } = await $fetch<CreatePetResponse>("/pets", {
    method: "POST",
    output: createPetResponseSchema,
    body,
  })
  if (error) throw error
  return data
}

export const updatePet = async ({ petId, body }: { petId: string; body: UpdatePetRequest }) => {
  const $fetch = await getClient()
  const path = buildPath("/pets/{petId}", { petId })
  const { data, error } = await $fetch<UpdatePetResponse>(path, {
    method: "PUT",
    output: updatePetResponseSchema,
    body,
  })
  if (error) throw error
  return data
}

export const deletePet = async ({ petId }: { petId: string }) => {
  const $fetch = await getClient()
  const path = buildPath("/pets/{petId}", { petId })
  const { data, error } = await $fetch<unknown>(path, {
    method: "DELETE",
  })
  if (error) throw error
  return data
}

