/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import * as z from "zod"

// Zod Schemas
export const petCategorySchema = z.enum(["dog", "cat", "bird", "fish", "reptile"])

export const petStatusSchema = z.enum(["available", "pending", "sold"])

export const petSchema = z.object({
  id: z.string(),
  name: z.string(),
  category: petCategorySchema,
  status: petStatusSchema,
  tags: z.array(z.string()),
  photoUrl: z.url().nullish(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime()
})

export const createPetInputSchema = z.object({
  name: z.string(),
  category: petCategorySchema,
  status: petStatusSchema,
  tags: z.array(z.string()),
  photoUrl: z.url().nullish()
})

export const updatePetInputSchema = z.object({
  name: z.string().nullish(),
  category: petCategorySchema.nullish(),
  status: petStatusSchema.nullish(),
  tags: z.array(z.string()).nullish(),
  photoUrl: z.url().nullish()
})

export const listPetsResponseSchema = z.object({
  data: z.array(petSchema),
  total: z.number().int()
})

export const listPetsParamsSchema = z.object({
  status: petStatusSchema.nullish(),
  category: petCategorySchema.nullish(),
  limit: z.number().int().nullish(),
  offset: z.number().int().nullish()
})

export const createPetRequestSchema = createPetInputSchema

export const createPetResponseSchema = petSchema

export const getPetResponseSchema = petSchema

export const getPetParamsSchema = z.object({
  petId: z.string()
})

export const updatePetRequestSchema = updatePetInputSchema

export const updatePetResponseSchema = petSchema

export const updatePetParamsSchema = z.object({
  petId: z.string()
})

export const deletePetParamsSchema = z.object({
  petId: z.string()
})

// TypeScript Types (inferred from Zod schemas)
export type PetCategory = z.infer<typeof petCategorySchema>
export type PetStatus = z.infer<typeof petStatusSchema>
export type Pet = z.infer<typeof petSchema>
export type CreatePetInput = z.infer<typeof createPetInputSchema>
export type UpdatePetInput = z.infer<typeof updatePetInputSchema>
export type ListPetsResponse = z.infer<typeof listPetsResponseSchema>
export type ListPetsParams = z.infer<typeof listPetsParamsSchema>
export type CreatePetRequest = z.infer<typeof createPetRequestSchema>
export type CreatePetResponse = z.infer<typeof createPetResponseSchema>
export type GetPetResponse = z.infer<typeof getPetResponseSchema>
export type GetPetParams = z.infer<typeof getPetParamsSchema>
export type UpdatePetRequest = z.infer<typeof updatePetRequestSchema>
export type UpdatePetResponse = z.infer<typeof updatePetResponseSchema>
export type UpdatePetParams = z.infer<typeof updatePetParamsSchema>
export type DeletePetParams = z.infer<typeof deletePetParamsSchema>
