/**
 * Code generation utilities using code-block-writer
 *
 * Provides a consistent, maintainable way to generate TypeScript code
 * with automatic indentation and formatting.
 */
import CodeBlockWriter from "code-block-writer";

/**
 * Create a configured CodeBlockWriter instance
 * Settings match biome.json formatter config:
 * - 2 spaces for indentation
 * - No tabs
 * - Unix newlines
 * - Double quotes
 */
export function createWriter(): CodeBlockWriter {
  return new CodeBlockWriter({
    indentNumberOfSpaces: 2,
    useTabs: false,
    newLine: "\n",
    useSingleQuote: false,
  });
}

/**
 * Write the standard auto-generated file header
 */
export function writeHeader(writer: CodeBlockWriter): void {
  writer.writeLine("/* eslint-disable */");
  writer.writeLine(
    "/* This file is auto-generated by tangrams. Do not edit. */",
  );
  writer.blankLine();
}

/**
 * Write an import statement with sorted named imports
 */
export function writeImport(
  writer: CodeBlockWriter,
  moduleSpecifier: string,
  namedImports: string[],
  isTypeOnly = false,
): void {
  if (namedImports.length === 0) return;

  const sorted = [...namedImports].sort();
  const typeKeyword = isTypeOnly ? "type " : "";
  writer.writeLine(
    `import ${typeKeyword}{ ${sorted.join(", ")} } from "${moduleSpecifier}"`,
  );
}

/**
 * Write a section comment
 */
export function writeSectionComment(
  writer: CodeBlockWriter,
  title: string,
): void {
  writer.writeLine(`// ${title}`);
}
