/* eslint-disable */
/* This file is auto-generated by tangrams. Do not edit. */

import { mutationOptions, queryOptions } from "@tanstack/react-query"

import { createPet, deletePet, getPetById, getPets, updatePet } from "../functions"

import type { CreatePetMutationVariables, DeletePetMutationVariables, GetPetByIdQueryVariables, GetPetsQueryVariables, UpdatePetMutationVariables } from "../schema"

// Query Options
export const getPetsQueryOptions = (variables?: GetPetsQueryVariables) =>
  queryOptions({
  queryKey: ["api", "GetPets", variables],
  queryFn: () => getPets(variables),
})

export const getPetByIdQueryOptions = (variables: GetPetByIdQueryVariables) =>
  queryOptions({
  queryKey: ["api", "GetPetById", variables],
  queryFn: () => getPetById(variables),
})

// Mutation Options
export const createPetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "CreatePet"],
  mutationFn: (variables: CreatePetMutationVariables) => createPet(variables),
})

export const updatePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "UpdatePet"],
  mutationFn: (variables: UpdatePetMutationVariables) => updatePet(variables),
})

export const deletePetMutationOptions = () =>
  mutationOptions({
  mutationKey: ["api", "DeletePet"],
  mutationFn: (variables: DeletePetMutationVariables) => deletePet(variables),
})

