import { useLiveQuery } from "@tanstack/react-db";
import { Link, createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: HomeComponent,
});

function HomeComponent() {
  const { collections } = Route.useRouteContext();

  // Get counts from both collections
  const { data: pets } = useLiveQuery(collections.pets);
  const { data: users } = useLiveQuery(collections.users);

  return (
    <div className="mx-auto max-w-4xl p-8">
      <div className="mb-8 text-center">
        <h1 className="text-4xl font-bold text-gray-900">
          Tangrams Full Stack Example
        </h1>
        <p className="mt-2 text-lg text-gray-600">
          A kitchen sink demo showcasing all tangrams generators
        </p>
      </div>

      {/* Feature Overview */}
      <div className="mb-8 rounded-lg border border-blue-200 bg-blue-50 p-6">
        <h2 className="mb-4 text-xl font-semibold text-blue-900">
          What this example demonstrates
        </h2>
        <ul className="space-y-2 text-blue-800">
          <li>
            <strong>TanStack Query</strong> - Generated query/mutation options
          </li>
          <li>
            <strong>TanStack Form</strong> - Generated form options with Zod
            validation
          </li>
          <li>
            <strong>TanStack DB</strong> - Generated collections with
            local-first mutations
          </li>
          <li>
            <strong>Full Sync Mode</strong> - Pets collection (all data fetched,
            client-side filtering)
          </li>
          <li>
            <strong>On-Demand Sync Mode</strong> - Users collection (predicates
            pushed to server)
          </li>
        </ul>
      </div>

      {/* Section Cards */}
      <div className="grid gap-6 md:grid-cols-2">
        {/* Pets Section */}
        <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-2xl font-bold text-gray-900">Pets</h2>
            <span className="rounded-full bg-green-100 px-3 py-1 text-sm font-medium text-green-800">
              Full Sync
            </span>
          </div>
          <p className="mb-4 text-gray-600">
            Local-first data with TanStack DB. All data is fetched and filtering
            happens client-side. Great for small to medium datasets.
          </p>
          <div className="mb-4 text-3xl font-bold text-gray-900">
            {pets.length}{" "}
            <span className="text-lg font-normal text-gray-500">pets</span>
          </div>
          <div className="flex gap-3">
            <Link
              to="/pets"
              className="rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
            >
              View Pets
            </Link>
            <Link
              to="/pets/new"
              className="rounded-lg border border-gray-300 px-4 py-2 text-gray-700 hover:bg-gray-50"
            >
              Add Pet
            </Link>
          </div>
        </div>

        {/* Users Section */}
        <div className="rounded-lg border border-gray-200 bg-white p-6 shadow-sm">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-2xl font-bold text-gray-900">Users</h2>
            <span className="rounded-full bg-purple-100 px-3 py-1 text-sm font-medium text-purple-800">
              On-Demand Sync
            </span>
          </div>
          <p className="mb-4 text-gray-600">
            Demonstrates predicate push-down. Filters are translated to API
            parameters and sent to the server. Great for large datasets.
          </p>
          <div className="mb-4 text-3xl font-bold text-gray-900">
            {users.length}{" "}
            <span className="text-lg font-normal text-gray-500">users</span>
          </div>
          <div className="flex gap-3">
            <Link
              to="/users"
              className="rounded-lg bg-purple-600 px-4 py-2 text-white hover:bg-purple-700"
            >
              View Users
            </Link>
            <Link
              to="/users/new"
              className="rounded-lg border border-gray-300 px-4 py-2 text-gray-700 hover:bg-gray-50"
            >
              Add User
            </Link>
          </div>
        </div>
      </div>

      {/* Tech Stack */}
      <div className="mt-8 rounded-lg border border-gray-200 bg-gray-100 p-6">
        <h2 className="mb-3 text-lg font-semibold text-gray-900">
          Generated by Tangrams
        </h2>
        <div className="grid gap-2 text-sm text-gray-600 sm:grid-cols-3">
          <div>
            <code className="text-gray-800">query/operations.ts</code>
            <p className="text-xs">TanStack Query options</p>
          </div>
          <div>
            <code className="text-gray-800">form/forms.ts</code>
            <p className="text-xs">TanStack Form options</p>
          </div>
          <div>
            <code className="text-gray-800">db/collections.ts</code>
            <p className="text-xs">TanStack DB collections</p>
          </div>
        </div>
      </div>
    </div>
  );
}
